### PR TITLE
Feature: Create landing page

### LINKED ISSUE #13: Create landing page for project

### PR DESCRIPTION
**Pull request by srimel**
Created a basic header component with nav. 

Also included a placeholder gif and "site under construction" message. I organized the components into their own folders, but was wondering if we should creat a parent folder called components? Also wasn't sure if I should put index in the components folder or not.. Also open to feedback for other file structure schemes!

I styled the page with a dark background and white text for the time being, figured we would have a separate user stories/spike for colors, design?

### CODE REVIEW

**Comment by elizasohn** [comment]
Looks awesome! Per our discussion, we should add a components folder and then will be ready to merge

**Comment by unfinishedideas** [comment]
Looking good! I agree about organizing the components in a separate folder. Will be good to have that separation in the file structure

**Review by anamika8 — APPROVED** [review]
Looks good to me!

**Comment by srimel** [comment]
@elizasohn @unfinishedideas Updated PR. Components now under a component directory.

**Pull request merged**
