### PR TITLE
Feature/testing stable diffusion api call

### LINKED ISSUE #56: Testing for Stable Diffusion Api Call

### PR DESCRIPTION
**Pull request by anamika8**
Here is a PR to add tests for the stable diffusion service that calls the Dezgo API to retrieve stable diffusion images by search text.

There are 3 tests:
1. Happy path testing
2. Negative test scenario where the API returns an error
3. Handling of the scenario where search text is not provided

Also added a random image file that will be needed to be read as binary to mock the return from the external API.
All tests are passing.

### CODE REVIEW

**Review by unfinishedideas — APPROVED** [review]
Looking good! Tests pass and cover a range of possible outcomes from the api

**Comment by unfinishedideas** [comment]
One comment I do have is that check-mark.png is inside the services folder when ./assets might be more appropriate

**Comment by unfinishedideas** [comment]
Sorry secondary comment - maybe we should put all of our tests into a tests folder. Something like './artscii/src/tests/'

**Review by elizasohn — APPROVED** [review]
looks good!

**Review by srimel — APPROVED** [review]
All test pass on my end and it seems like you have good coverage here - great job!

**Pull request merged**
