### PR TITLE
Feature/setup routing

### LINKED ISSUE #16: Set up react routing
As a user, I would like to be shown different pages when I click on different page titles so that I can navigate through the site

Points: 3

### PR DESCRIPTION
**Pull request by elizasohn**

### CODE REVIEW

**Comment by unfinishedideas** [comment]
Nice job look good!

**Review by unfinishedideas — APPROVED** [review]
Looks good to me!

**Review by anamika8 — APPROVED** [review]
Looks nicer and cleaner!

**Review by srimel — APPROVED** [review]
Great work!

**Pull request merged**
