### PR TITLE
Create about page

### LINKED ISSUE #21: Create 'about' page or section
As a user, I want an 'About' page (section?) that explains the purpose behind this website, so that I can understand what is happening and the purpose of the web app.

Acceptance Criteria:
- New page (section?) linked to the 'About' navbar-link
- Explains our motivation for the website and how to use the interface
- User able to navigate back to home page if on new page

### PR DESCRIPTION
**Pull request by srimel**
So, I wrote some stuff for the about page. I'd definitely like input on anything else I could include or change. Going to leave this as a draft PR for now. Should we include any information on ourselves, the developers? Open to any and all feedback!

### CODE REVIEW

**Review by unfinishedideas — APPROVED** [review]
All glory to the hypno toad!
I'm liking the about page I think it's g2g

**Comment by elizasohn** [comment]
Great write up! I can't really read the "click here" text though in that color. Maybe if we could use something a little lighter? I also would get rid of the cursive to keep the style consistent. I love the frog! It also makes me think we could make another ticket to underline whichever page the user is on in the nav/header rather than adding the title to the component.

**Comment by srimel** [comment]
Updated the PR:
- removed the about page title, @elizasohn had a good idea about indicating current page with navbar underlining
- rolled back the cursive font
- changed link colors to lighter palette

**Comment by elizasohn** [comment]
updates look great!

**Review by elizasohn — APPROVED** [review]

**Pull request merged**
